In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedShuffleSplit

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

In [2]:
# 데이터 불러오기 - iris
iris = pd.read_csv('./Data/iris.csv')

In [3]:
# 데이터 프레임 확인
iris

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [36]:
# 단순임의추출방법
# DataFrame.sample()
# parameters
# n = 단순임의추출 표본개수
# frac = DataFrame의 표본개수의 frac을 곱한 수만큼 데이터양을 증가시킴
#   L frac이 1보다 크면, replace = True를 반드시 설정 
#   L axis =1 이면 컬럼의 수를 증가시키고, axis = 0이면 행의 수를 증가시킨다.
iris.sample(frac = 5, replace = True, random_state = 10, axis = 0 )

     sepal_length  sepal_width  petal_length  petal_width            class
9             4.9          3.1           1.5          0.1      Iris-setosa
125           7.2          3.2           6.0          1.8   Iris-virginica
15            5.7          4.4           1.5          0.4      Iris-setosa
64            5.6          2.9           3.6          1.3  Iris-versicolor
113           5.7          2.5           5.0          2.0   Iris-virginica
..            ...          ...           ...          ...              ...
137           6.4          3.1           5.5          1.8   Iris-virginica
75            6.6          3.0           4.4          1.4  Iris-versicolor
30            4.8          3.1           1.6          0.2      Iris-setosa
46            5.1          3.8           1.6          0.2      Iris-setosa
79            5.7          2.6           3.5          1.0  Iris-versicolor

[750 rows x 5 columns]

In [101]:
"""
층화추출방법 : 모집단이 이질적인 몇 개의 계층으로 이루어져 있을 때 모든 계층으로부터
원소를 임의로 추출하여 각 계층을 고루 대표할 수 있도록 랜덤하게 표본을 추출하는 방법
"""
# 층화임의추출
# from sklearn.model_selection import train_test_split
# parameters
# *arrays => 데이터 프레임
# stratify => 주로 y값을 층화추출의 기준으로 잡는다
x_train, x_test, y_train, y_test = train_test_split(iris.drop('class', axis = 1), iris['class'], random_state = 1, train_size = 0.7,  stratify = iris['class'])
len(y_train[y_train == 'Iris-virginica']),len(y_train[y_train == 'Iris-setosa']),len(y_train[y_train == 'Iris-versicolor'])

(35, 35, 35)

In [88]:
# 층화임의추출
# setosa 20개, versicolor 15개, verginica 15개씩 추출하기
# from sklearn.model_selection import StratifiedShuffleSplit
for  train_index, test_index in StratifiedShuffleSplit(n_splits=3, train_size = 0.7, random_state = 10).split(iris.drop('class', axis = 1), iris['class']):
    x_train, x_test = iris.drop('class', axis = 1).iloc[train_index], iris.drop('class', axis = 1).iloc[test_index]
    y_train, y_test = iris['class'].iloc[train_index], iris['class'].iloc[test_index]    
len(y_train[y_train == 'Iris-virginica']),len(y_train[y_train == 'Iris-setosa']),len(y_train[y_train == 'Iris-versicolor'])

(35, 35, 35)

In [146]:
# 층화임의추출
def stratify_random_samplint(data, n_samples, y_name):
    data_y = data[y_name].unique()
    if n_samples % len(data_y) == 0:
        df_list = list()
        n_samples_list = list()
        for idx, val in enumerate(data_y):
            df_tmp = data[data[y_name] == data_y[idx]]
            ratio_tmp = round(len(df_tmp)/data.shape[0], 2)
            tmp_samples = int(n_samples*ratio_tmp)
            df_tmp2 = df_tmp.sample(n = tmp_samples, axis = 0)
            df_list.append(df_tmp2)
        results = pd.concat(df_list,axis = 0 )
        return results
    else:
        df_list = list()
        n_samples_list = list()
        for idx, val in enumerate(data_y):
            df_tmp = data[data[y_name] == data_y[idx]]
            ratio_tmp = round(len(df_tmp)/data.shape[0], 2)
            tmp_samples = int(n_samples*ratio_tmp)
            df_tmp2 = df_tmp.sample(n = tmp_samples, axis = 0)
            df_list.append(df_tmp2)
        df_list.append(correction)
        results = pd.concat(df_list,axis = 0 )       
        return results

In [147]:
stratify_random_samplint(iris, 67, 'class')

     sepal_length  sepal_width  petal_length  petal_width           class
45            4.8          3.0           1.4          0.3     Iris-setosa
20            5.4          3.4           1.7          0.2     Iris-setosa
47            4.6          3.2           1.4          0.2     Iris-setosa
15            5.7          4.4           1.5          0.4     Iris-setosa
32            5.2          4.1           1.5          0.1     Iris-setosa
..            ...          ...           ...          ...             ...
115           6.4          3.2           5.3          2.3  Iris-virginica
106           4.9          2.5           4.5          1.7  Iris-virginica
128           6.4          2.8           5.6          2.1  Iris-virginica
137           6.4          3.1           5.5          1.8  Iris-virginica
138           6.0          3.0           4.8          1.8  Iris-virginica

[67 rows x 5 columns]